const images = {
   App_logo: require('./one_fifty.png'),
   App_logo_AIM: require('./logo1024x1024.png'),
   App_logo_map: require('./aimge-logo.png'),
   Color_picker_image: require('./thirty.png'),
   First_Swiper: require('./LottieAnimation/first_swiper.json'),
   // First_Swiper: require('./LottieAnimation/first-swiper.json'),
   Two_Swiper: require('./LottieAnimation/FirstSwiper.json'),
   Three_Swiper: require('./LottieAnimation/swiper_third.json'),
   // Three_Swiper: require('./LottieAnimation/three-swiper.json'),
   Splash_Swiper: require('./LottieAnimation/SplashScreen.json'),
   Account_created: require('./LottieAnimation/Accountcreated.json'),
   Reviewsimage_screen: require('./LottieAnimation/Reviewsimage.json'),
   Languageanimation: require('./LottieAnimation/languageanimation.json'),
   SpeedMeter: require('./LottieAnimation/speed-test.json'),
   carAuto: require('./LottieAnimation/carAuto2.json'),
   fuel_pump: require('./LottieAnimation/eco-fuel.json'),
   carclouds: require('./LottieAnimation/car.json'),
   Google_image: require('./googleicon.png'),
   Avatar: require('./avatar-placeholder.png'),
   Card: require('./credircard.png'),
   GalleryIcon: require('./image-gallery.png'),
   CameraIcon: require('./photo-camera.png'),
   User_image_one_profile: require('./hundred.png'),
   HomeCarOne: require('./Nayel_bike_3.8.png'),  
   Transaction: require('./aim.png'),
   Homeuserone: require('./hundred.png'),
   Pymentsuceeful_img: require('./two_hundred.png'),
   dateIcon: require('./twenty_five.png'),
   timeIcon: require('./twenty_five.png'),
   clockIcon: require('./twenty_five.png'),
   gpay_upi_img: require('./upiicon.png'),
   // paytem_img: require('./paytem.png'),
   landing_screen: require('./LottieAnimation/loader_landing_screen.json'),
   profile_screen: require('./LottieAnimation/profileScreenLoader.json'),
   transaction_screen: require('./LottieAnimation/cardLoader.json'),
   Mobikwikimage_img: require('./Mobikwikimage.png'),
   freechargelogo_img: require('./freechargelogo.png'),
   gpay_img: require('./gpaylogoimage.png'),
   paypal_img: require('./paypal.png'),
   creditcard_img: require('./creditcardimage.png'),
   steering: require('./twenty.png'),
   diesel: require('./twenty.png'),
   carseat: require('./twenty.png'),
   highperformance: require('./twenty.png'),
   calendarIcon: require('./twenty.png'),
   location: require('./hundred.png'),
   Bike_1: require('./hundred.png'),
   Bike_2: require('./hundred.png'),
   Bike_3: require('./hundred.png'),
   Car_1: require('./Nayel_bike_3.8.png'),
   Car_2: require('./hundred.png'),
   notification_1: require('./hundred.png'),
   notification_2: require('./hundred.png'),
}
export default images;