const RouteName = {
    SPLASH: "SplashScreen",
    SWIPER_SCREEN: "Swiperscreen",
    LOGIN_SCREEN: "LoginScreen",
    REGISTER_SCREEN: "Register",
    OTP_VERIFY_SCREEN: 'OtpVeryfiveScreen',
    HOME_SCREEN: "HomeScreen",
    REGISTRATION_SUCCESSFUL: "RegistrationSuccessful",
    HOME_TAB: 'Home',
    CATEGORY_TAB: 'CategoryTab',
    FAVORITE_TAB: 'FavouriteTab',
    PROFILE_TAB: 'Profile',
    SELECT_LANGUAGE: 'TranslationScreen',
    Forget_Password: 'ForgotPassword',
    CHAT_SCREEN: 'Chatscreen',
    HELP_SCREEN: 'HelpScreen',
    SETTING_SCREEN: 'SettingsScreen',
    FAQ_SCREEN: 'FAQScreen',
    REVIEWS_SCREEN: 'ReviewsScreen',
    NOTIFICATION_SCREEN: 'NotificationScreen',
    DETAILS_SCREEN: "DetailsScreen",
    PAYMENT_SCREEN: "PaymentScreen",
    PAYMENT_SUCCESSFUL_SCREEN: "PaytmSuccessFully",
    SECRET_CARD_SCREEN: "SecretcardsScreen",
    DATE_AND_TIME_SCREEN: "DateAndTimeScreen",
    RENT_PLANS_SCREEN: "RentPlansScreen",
    ADD_A_BIKE: "AddABike",
    TRANSACTION_LIST: "TransactionList",
    SECRET_FULL_SCREEN: "secretfullscreen",
    CARDS_SCREEN: 'CardsScreen',
    CHANGE_CARD_PIN:'ChangePin',
    // QRCODE_GENERATE: 'QRCodeGenerate',
    // QRCODE_SCAN: 'QRCodeScan'
}
export default RouteName;