export * from './Authentication';
export * from './Home';
export * from './SplashScreen';
export * from './SwiperScreen';
export * from './ChatScreen';
export * from './SettingsScreen';
export * from './HelpScreen';
export * from './FAQScreen';
export * from './ReviewsScreen';
export * from './Notification';
export * from './DetailsScreen';
export * from './PaymentScreen';
export * from './DateAndTimeScreen';
export * from './RentPlansScreen';
export * from './BookABikrForm';
export * from './LocationScreen';
export * from './CardsScreen';
export * from './ScanScreen';

